# Generated by Django 6.1 on 2026-08-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_memberprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='phone_number',
        ),
    ]
