# Generated by Django 6.1 on 2026-08-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
